### ISSUE TITLE
Models added twice to a virtual collection

### ISSUE THREAD

**Issue by bendulum** [p3drosola/Backbone.VirtualCollection#62]
I might have found a bug in the following scenario: 
When a new model is created and added to the superset, the subset collection will also add it if it passes the filter.
After the model is persisted on the server it receives a new id value. (In my setup from a negative integer to a positive integer).
This will trigger the ``_onChange`` handler in VirtualCollection, which is supposed to check if the affected model is already in the subset. If not, and the model passes the filter, it will be added.
In this scenario the line ``var already_here = this.get(model);`` does not find the model, therefore the model is added *again* to the subset.
I have managed to bypass this behavior by prototyping the ``get`` method inside VirtualCollection to read:
````
get: function(obj) {
    if (obj == null) return void 0;
    return this._byId[obj.cid ? obj.cid : obj.id || obj];
},
````
It seems to work now that the model is not added again, but I'm unsure if this is a valid solution, if it might break other things or have a negative impact on performance.
Can anyone verify that this is a bug in VirtualCollection or perhaps intended behavior or a missing feature?

**Comment by chearon** [comment]
That couldn't happen since the `change` event fires after the id has already been updated, in which case `get` would return the model with the updated ID. I can't think of a case where it's possible for `change` to happen before `id` is set... Did you perhaps modify/override Backbone's `set` or something?

```javascript
  var model = new Backbone.Model({id: 0});

  var superset = new Backbone.Collection([model]);

  var subset = new VirtualCollection(superset, {
    filter: function (model) {
      return model.id >= 0;
    }
  });

  console.log(subset.length);

  model.set({id: 2});

  console.log(subset.length);
```

Output:
```
1
1
```

**Comment by p3drosola** [comment]
Can you provide a failing test case @bendulum ?

**Comment by bendulum** [comment]
I will investigate further, one thing that is special to my scenario is that the superset of the affected subset is another VirtualCollection. So in essence there is ``global collection > subset 1 > subset 2`` whereas the bug appears in ``subset 2``.

**Comment by bendulum** [comment]
Can you confirm this @p3drosola 

````
var model1 = new Backbone.Model({id: -1, some: true, other: true});
var model2 = new Backbone.Model({id: -2, some: true, other: true});
var model3 = new Backbone.Model({id: -3, some: true});
var model4 = new Backbone.Model({id: -4});

var superset = new Backbone.Collection([model1, model2, model3, model4]);

var subset1 = new VirtualCollection(superset, {
    filter: function (model) {
        return model.get('some');
    }
});

var subset2 = new VirtualCollection(subset1, {
    filter: function (model) {
        return model.get('other');
    }
});

console.log(subset1.length, subset2.length);

model2.set({id: 2});
model3.set({id: 3});

console.log(subset1.length, subset2.length);
````
Output:
````
3 2
5 3
````
Is this a bug or am I missing something?

**Comment by p3drosola** [comment]
Hi @bendulum, 

That bug was fixed in [0.5.3](https://github.com/p3drosola/Backbone.VirtualCollection/wiki/Changelog#053).

 I just noticed the version on NPM was lagging behind, and pushed the latest to npm.

If you update your package it should work fine now.

Thanks for reporting this.

**Comment by bendulum** [comment]
i'm not using npm actually, i'm using the files from the dist directory in
this repository. could you update those aswell?

**Comment by bendulum** [comment]
FYI Using the latest version from [here](https://github.com/p3drosola/Backbone.VirtualCollection/blob/master/src/backbone.virtual-collection.js) the test case i provided above i still failing for me.
I did not modify or override anything in backbone.
